import streamlit as st
import time
import sys
import os

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from config import load_recommendations, save_recommendations, load_vendors
except:
    st.error("⚠️ Missing config.py file. Please ensure all files are in the correct location.")
    st.stop()

st.title("✅ Approval Queue")

# Load recommendations
recommendations = load_recommendations()
vendors = load_vendors()

# Count active recommendations
active_recs = [r for r in recommendations if r.get('status') == 'pending']

st.markdown(f"Review **{len(active_recs)}** AI-generated recommendations and approve or reject with one tap.")

# Add AI confidence badge
st.info("🤖 **AI-Powered Recommendations** | All suggestions below were generated by analyzing your sales data, inventory levels, and market conditions.")

st.markdown("---")

# Initialize session state
if 'processed_ids' not in st.session_state:
    st.session_state.processed_ids = set()

# Check if we have any recommendations
if not recommendations or len(active_recs) == 0:
    st.warning("⚠️ No recommendations available yet.")
    st.markdown("""
    **To generate recommendations:**
    1. Go to **Data Sources** page
    2. Upload your sales CSV file
    3. Click **"Process Data with AI"**
    4. Return here to review AI recommendations
    """)
    
    if st.button("📤 Go to Data Sources", key="goto_datasources", type="primary"):
        st.switch_page("pages/2_📤_Data_Sources.py")
    
    # Show sample recommendations if none exist
    st.markdown("---")
    st.markdown("### 🎬 Sample Demo Recommendations")
    st.info("These are sample recommendations to show you how the system works. Upload real data to see actual AI analysis!")
    
    # Create sample recommendations for demo
    sample_recs = [
        {
            "id": "demo_1",
            "type": "REORDER",
            "product": "Red Bull",
            "recommended_quantity": 48,
            "current_stock": 8,
            "weekly_velocity": 36,
            "reason": "Sales are up 20% on Fridays, and current stock is low.",
            "confidence": 94,
            "ai_agent": "Reorder Agent (GPT-4)",
            "status": "pending"
        },
        {
            "id": "demo_2",
            "type": "PROMOTION",
            "product": "Croissants",
            "recommended_quantity": 20,
            "current_stock": 20,
            "reason": "Stock is high (20 units) and items may expire soon. Create 50% off deal to avoid waste.",
            "confidence": 91,
            "ai_agent": "Promotion Agent (Claude 3.5)",
            "status": "pending"
        }
    ]
    recommendations = sample_recs

# Display recommendations
for rec in recommendations:
    # Skip if already processed in this session
    rec_id = rec.get('id', str(rec.get('product', '')))
    if rec_id in st.session_state.processed_ids:
        continue
    
    # Skip if not pending
    if rec.get('status') not in ['pending', None]:
        continue
    
    # Determine recommendation type
    rec_type = rec.get('type', 'REORDER')
    
    # Set icon based on type
    if rec_type == 'REORDER':
        icon = "🔄"
        title = f"REORDER: {rec.get('product', 'Unknown Product')}"
    elif rec_type == 'PROMOTION':
        icon = "🏷️"
        title = f"PROMOTION: {rec.get('product', 'Unknown Product')}"
    else:
        icon = "💬"
        title = f"NEGOTIATE: {rec.get('product', 'Unknown Product')}"
    
    with st.container(border=True):
        # Header with icon and title
        st.markdown(f"## {icon} {title}")
        
        # AI Agent Badge
        col_badge1, col_badge2 = st.columns([3, 1])
        with col_badge1:
            ai_agent = rec.get('ai_agent', 'Reorder Agent (GPT-4)')
            st.markdown(f"🤖 **Generated by:** {ai_agent}")
        with col_badge2:
            confidence = rec.get('confidence', 85)
            st.markdown(f"**Confidence:** {confidence}%")
        
        st.markdown("---")
        
        # Recommendation details
        if rec_type == 'REORDER':
            st.markdown(f"### 📋 Recommendation")
            qty = rec.get('recommended_quantity', 0)
            st.markdown(f"**Order {qty} units**")
            
            # Find matching vendor
            product = rec.get('product', '')
            matching_vendor = None
            for vendor in vendors:
                if product in vendor.get('products', []) or any(product.lower() in p.lower() for p in vendor.get('products', [])):
                    matching_vendor = vendor
                    break
            
            if matching_vendor:
                st.markdown(f"**Vendor:** {matching_vendor['name']}")
                st.markdown(f"**Order Method:** {matching_vendor['order_method'].title()}")
                st.markdown(f"**Contact:** {matching_vendor.get('email', matching_vendor.get('contact', 'N/A'))}")
        
        elif rec_type == 'PROMOTION':
            st.markdown(f"### 📋 Recommendation")
            st.markdown(f"**Create 50% off promotion to move {rec.get('current_stock', 0)} units**")
            st.markdown("**Suggested:** End-of-day flash sale")
        
        else:  # NEGOTIATE
            st.markdown(f"### 📋 Recommendation")
            st.markdown("**Draft negotiation email to supplier for better pricing**")
        
        # Explain Why section
        with st.expander("🤔 Explain Why? (AI Reasoning)", expanded=False):
            st.markdown(f"**AI Analysis:** {rec.get('reason', 'No reason provided')}")
            st.markdown("---")
            st.markdown("**Key Metrics:**")
            
            if 'current_stock' in rec:
                st.markdown(f"- **Current Stock:** {rec['current_stock']} units")
            if 'weekly_velocity' in rec:
                st.markdown(f"- **Weekly Sales:** {rec['weekly_velocity']} units/week")
            if 'growth_rate' in rec and rec['growth_rate'] > 0:
                st.markdown(f"- **Growth Trend:** +{rec['growth_rate']}%")
            if 'recommended_quantity' in rec:
                st.markdown(f"- **Recommended Order:** {rec['recommended_quantity']} units")
            
            # AI model info
            st.markdown("---")
            st.markdown("**AI Processing:**")
            st.markdown("- Time-series forecasting (ARIMA)")
            st.markdown("- Pattern recognition with ML")
            st.markdown("- Inventory optimization algorithms")
        
        # Action buttons
        col1, col2, col3 = st.columns([1, 1, 3])
        
        with col1:
            if st.button("✅ Approve", key=f"approve_{rec_id}", type="primary", use_container_width=True):
                # Update recommendation status
                for i, r in enumerate(recommendations):
                    if r.get('id', str(r.get('product', ''))) == rec_id:
                        recommendations[i]['status'] = 'approved'
                        recommendations[i]['approved_at'] = time.strftime('%Y-%m-%d %H:%M:%S')
                        break
                
                save_recommendations(recommendations)
                st.session_state.processed_ids.add(rec_id)
                
                st.success(f"✅ Approved! Recommendation will be executed.")
                
                # Show execution options for reorders
                if rec_type == 'REORDER' and matching_vendor:
                    time.sleep(1)
                    st.markdown("---")
                    st.markdown("### 📤 Execute Order")
                    
                    order_method = matching_vendor['order_method']
                    
                    if order_method == 'email':
                        st.info(f"📧 Preparing email to {matching_vendor['email']}...")
                        with st.expander("View Draft Email"):
                            st.code(f"""
To: {matching_vendor['email']}
Subject: Order Request - {product}

Dear {matching_vendor['name']},

I would like to place an order for:
- Product: {product}
- Quantity: {qty} units

Please confirm availability and delivery timeline.

Thank you!
                            """)
                        if st.button("Send Email", key=f"send_email_{rec_id}"):
                            st.success("✅ Email sent!")
                    
                    elif order_method == 'phone':
                        st.info(f"📞 Call {matching_vendor['contact']} to place order")
                        if st.button("Mark as Ordered", key=f"mark_ordered_{rec_id}"):
                            st.success("✅ Marked as ordered!")
                    
                    elif order_method == 'whatsapp':
                        st.info(f"💬 Send WhatsApp to {matching_vendor['contact']}")
                        message = f"Hi! I'd like to order {qty} units of {product}. Please confirm."
                        st.code(message)
                        if st.button("Open WhatsApp", key=f"whatsapp_{rec_id}"):
                            st.success("✅ Opening WhatsApp...")
                    
                    elif order_method == 'website':
                        st.info(f"🌐 Place order on vendor website")
                        if st.button("Mark as Ordered Online", key=f"web_ordered_{rec_id}"):
                            st.success("✅ Marked as ordered!")
                
                time.sleep(1)
                st.rerun()
        
        with col2:
            if st.button("❌ Reject", key=f"reject_{rec_id}", use_container_width=True):
                # Update recommendation status
                for i, r in enumerate(recommendations):
                    if r.get('id', str(r.get('product', ''))) == rec_id:
                        recommendations[i]['status'] = 'rejected'
                        recommendations[i]['rejected_at'] = time.strftime('%Y-%m-%d %H:%M:%S')
                        break
                
                save_recommendations(recommendations)
                st.session_state.processed_ids.add(rec_id)
                
                st.warning(f"❌ Rejected. AI will learn from your feedback.")
                time.sleep(1)
                st.rerun()
        
        st.markdown("---")

# Show completion message if all processed
active_remaining = [r for r in recommendations if r.get('status') == 'pending' and r.get('id', str(r.get('product', ''))) not in st.session_state.processed_ids]

if len(recommendations) > 0 and len(active_remaining) == 0:
    st.balloons()
    st.success("🎉 All AI recommendations have been processed!")
    
    # Count approved/rejected
    approved_count = len([r for r in recommendations if r.get('status') == 'approved'])
    rejected_count = len([r for r in recommendations if r.get('status') == 'rejected'])
    
    st.markdown("### Summary")
    col1, col2 = st.columns(2)
    with col1:
        st.metric("✅ Approved", approved_count)
    with col2:
        st.metric("❌ Rejected", rejected_count)
    
    st.info("💡 The AI agents will learn from your decisions to improve future recommendations!")
    
    if st.button("🔄 Clear Queue & Reload", type="secondary", key="reset_queue"):
        st.session_state.processed_ids = set()
        st.rerun()

# Show processed items at the bottom
if st.session_state.processed_ids:
    st.markdown("---")
    st.markdown("### 📋 Recently Processed")
    
    approved_items = [r for r in recommendations if r.get('status') == 'approved']
    rejected_items = [r for r in recommendations if r.get('status') == 'rejected']
    
    if approved_items:
        with st.expander(f"✅ Approved Items ({len(approved_items)})", expanded=False):
            for rec in approved_items:
                icon = "🔄" if rec.get('type') == 'REORDER' else "🏷️" if rec.get('type') == 'PROMOTION' else "💬"
                product = rec.get('product', 'Unknown')
                st.markdown(f"- {icon} {product} (Confidence: {rec.get('confidence', 85)}%)")
    
    if rejected_items:
        with st.expander(f"❌ Rejected Items ({len(rejected_items)})", expanded=False):
            for rec in rejected_items:
                icon = "🔄" if rec.get('type') == 'REORDER' else "🏷️" if rec.get('type') == 'PROMOTION' else "💬"
                product = rec.get('product', 'Unknown')
                st.markdown(f"- {icon} {product}")